name: Production infra build

on:
    push:
        branches:
            - main
        paths:
          - aws_resources/*
jobs:
  terraform:
    name: "Terraform CDK Deploy"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install
        working-directory: aws_resources

      - name: Generate module and provider bindings
        run: npx cdktf-cli get
        working-directory: aws_resources

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.31
        with:
          terraformVersion: 1.3.0
          cdktfVersion: 0.11.2
          stackName: StaticWebsiteStack
          mode: auto-approve-apply
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: aws_resources
        